/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AISSAN Francois
 */
public class Liste_fournisseur extends javax.swing.JPanel {

    /**
     * Creates new form Liste_utilisateurs
     */
    public Liste_fournisseur() {
        initComponents();
        Font myFont2 = new Font("Yu Gothic UI Semilight", Font.BOLD, 16);

        liste_four_table.getTableHeader().setFont(myFont2);
        dtm.addColumn("Référence");
        dtm.addColumn("Nom");
        dtm.addColumn("Adresse");
        dtm.addColumn("Téléphone");

        try {
                //connexion à la base de données
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                    co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=latin1","root","");
                    st = co.createStatement();    
                    resultat = st.executeQuery("SELECT reference_fournisseur, nom_fournisseur,adresse_fournisseur,telephone_fournisseur FROM fournisseur");
                    
                    while(resultat.next())
                    {            
                        dtm.addRow(new Object[]{resultat.getObject(1),resultat.getObject(2),resultat.getObject(3),resultat.getObject(4)});
                    }
                    
                    liste_four_table.setModel(dtm);
        } catch (Exception e) {
            System.out.println("ERROR");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_fournisseur = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        essai = new javax.swing.JPanel();
        modif_fournisseur = new produitbio.Button_perso();
        jPanel4 = new javax.swing.JPanel();
        ajout_four = new produitbio.Button_perso();
        supprimer = new produitbio.Button_perso();
        jScrollPane2 = new javax.swing.JScrollPane();
        liste_four_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(217, 217, 217));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel_fournisseur.setBackground(new java.awt.Color(217, 217, 217));
        jPanel_fournisseur.setPreferredSize(new java.awt.Dimension(1596, 619));
        jPanel_fournisseur.setLayout(null);
        jPanel_fournisseur.add(jSeparator1);
        jSeparator1.setBounds(244, 101, 935, 2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Liste des fournisseurs");
        jPanel_fournisseur.add(jLabel2);
        jLabel2.setBounds(45, 79, 195, 22);

        essai.setBackground(new java.awt.Color(217, 217, 217));
        essai.setToolTipText("");

        javax.swing.GroupLayout essaiLayout = new javax.swing.GroupLayout(essai);
        essai.setLayout(essaiLayout);
        essaiLayout.setHorizontalGroup(
            essaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        essaiLayout.setVerticalGroup(
            essaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jPanel_fournisseur.add(essai);
        essai.setBounds(586, 30, 1010, 33);

        modif_fournisseur.setBackground(new java.awt.Color(255, 153, 51));
        modif_fournisseur.setForeground(new java.awt.Color(51, 51, 51));
        modif_fournisseur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-plus-25.png"))); // NOI18N
        modif_fournisseur.setText("Modifier");
        modif_fournisseur.setBorderColor(new java.awt.Color(255, 153, 51));
        modif_fournisseur.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        modif_fournisseur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modif_fournisseur.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        modif_fournisseur.setIconTextGap(5);
        modif_fournisseur.setRadius(18);
        modif_fournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modif_fournisseurMouseClicked(evt);
            }
        });
        jPanel_fournisseur.add(modif_fournisseur);
        modif_fournisseur.setBounds(249, 40, 137, 33);

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1227, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jPanel_fournisseur.add(jPanel4);
        jPanel4.setBounds(1416, 522, 1227, 413);

        ajout_four.setBackground(new java.awt.Color(0, 169, 54));
        ajout_four.setForeground(new java.awt.Color(51, 51, 51));
        ajout_four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-plus-25.png"))); // NOI18N
        ajout_four.setText("Ajouter");
        ajout_four.setBorderColor(new java.awt.Color(0, 169, 54));
        ajout_four.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        ajout_four.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ajout_four.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ajout_four.setIconTextGap(5);
        ajout_four.setRadius(18);
        ajout_four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajout_fourMouseClicked(evt);
            }
        });
        jPanel_fournisseur.add(ajout_four);
        ajout_four.setBounds(55, 40, 145, 33);

        supprimer.setBackground(new java.awt.Color(255, 102, 102));
        supprimer.setForeground(new java.awt.Color(51, 51, 51));
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-supprimer-pour-toujours-25.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setBorderColor(new java.awt.Color(255, 102, 102));
        supprimer.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        supprimer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supprimer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        supprimer.setIconTextGap(5);
        supprimer.setRadius(18);
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerMouseClicked(evt);
            }
        });
        jPanel_fournisseur.add(supprimer);
        supprimer.setBounds(445, 40, 135, 33);

        liste_four_table.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        liste_four_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(liste_four_table);

        jPanel_fournisseur.add(jScrollPane2);
        jScrollPane2.setBounds(45, 114, 1160, 402);

        jPanel2.add(jPanel_fournisseur, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer?", "SUPPRESSION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
               Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=utf-8","root","");
                //Recupération de la référence du produit à supprimer dans la table
                DefaultTableModel table = (DefaultTableModel)liste_four_table.getModel();
                //Ligne sélectionnée
                int rowindex = liste_four_table.getSelectedRow();
                //Référence se trouve sur la colonne 0, ligne selectionnée
               String ref =(String) liste_four_table.getValueAt(rowindex,0).toString().trim();  
                //Requete de suppression du produit
                String sql = "DELETE FROM fournisseur where reference_fournisseur ='"+ref+"'";
                //Création de l'objet statement
                st = co.createStatement();
                //Exécution de la requête
                st.executeUpdate(sql);
                //fermeture de la connexion
                co.close();
                //Suppression de la ligne de la table
                table.removeRow(rowindex);
                //Message de suppression
                JOptionPane.showMessageDialog(null, "Données supprimées");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Problème de suppression");
            }
        }    
    }//GEN-LAST:event_supprimerMouseClicked
             
    private void modif_fournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modif_fournisseurMouseClicked
       TableModel model = (TableModel) liste_four_table.getModel();
       int index =liste_four_table.getSelectedRow();
       Modification_fournisseur jtRowData = new Modification_fournisseur();
       System.out.println(model.getValueAt(index, 0));
       String ref = model.getValueAt(index,0).toString();
       String nom = model.getValueAt(index,1).toString();
       String adr = model.getValueAt(index,2).toString();
       String tel = model.getValueAt(index,3).toString();
       jtRowData.setVisible(true);
       jtRowData.pack();
       jtRowData.name_fournisseur.setText(nom);
       jtRowData.adr_fournisseur.setText(adr);
       jtRowData.tel_fournisseur.setText(tel);
       jtRowData.ref_fournisseur.setText(ref);
    }//GEN-LAST:event_modif_fournisseurMouseClicked

    private void ajout_fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajout_fourMouseClicked
        new Nouveau_fournisseur().setVisible(true);
    }//GEN-LAST:event_ajout_fourMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajout_four;
    private javax.swing.JPanel essai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_fournisseur;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable liste_four_table;
    private produitbio.Button_perso modif_fournisseur;
    private produitbio.Button_perso supprimer;
    // End of variables declaration//GEN-END:variables
    Connection co;
    Statement st;
    ResultSet resultat;
    DefaultTableModel dtm = new DefaultTableModel();

}
