/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AISSAN Francois
 */
public class Liste_produit extends javax.swing.JPanel {

    /**
     * Creates new form Liste_utilisateurs
     */
    public Liste_produit() {
        initComponents();
        Font myFont2 = new Font("Yu Gothic UI Semilight", Font.BOLD, 16);

        liste_produit.getTableHeader().setFont(myFont2);
        dtm.addColumn("Référence");
        dtm.addColumn("Libellé");
        dtm.addColumn("Date production");
        dtm.addColumn("Date expiration");
        dtm.addColumn("Quantité");
        dtm.addColumn("Quantité alerte");
        dtm.addColumn("Prix de vente");
        dtm.addColumn("Categorie");
        
        try {
                //connexion à la base de données
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                    co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=utf-8","root","");
                    st = co.createStatement();    
                    resultat = st.executeQuery("SELECT * FROM produit");
                    SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");

                    while(resultat.next())
                    {
                        
                        //Object date_prod = sdf.parse((String) resultat.getObject(3));
                        //Object date_exp = sdf.parse((String)resultat.getObject(4));
                        //Object obj1 = date_prod;
                        //Object obj2 = date_exp;
                        //System.out.println(f.format(resultat.getObject(3)));
                        
                        dtm.addRow(new Object[]{resultat.getObject(1),resultat.getObject(2),resultat.getObject(3),resultat.getObject(4),resultat.getObject(5),resultat.getObject(6),resultat.getObject(7),resultat.getObject(8)});
                    }
                    liste_produit.setModel(dtm);
        } catch (Exception e) {
            System.out.println("ERROR");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        liste_user_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ajout_produit = new produitbio.Button_perso();
        supprimer_produit = new produitbio.Button_perso();
        jPanel4 = new javax.swing.JPanel();
        modifier_produit = new produitbio.Button_perso();
        ajout_categorie = new produitbio.Button_perso();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste_produit = new javax.swing.JTable();

        liste_user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(liste_user_table);

        setBackground(new java.awt.Color(217, 217, 217));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Liste des produits");

        ajout_produit.setBackground(new java.awt.Color(0, 169, 54));
        ajout_produit.setForeground(new java.awt.Color(51, 51, 51));
        ajout_produit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-plus-25.png"))); // NOI18N
        ajout_produit.setText("Ajouter un produit");
        ajout_produit.setBorderColor(new java.awt.Color(0, 169, 54));
        ajout_produit.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        ajout_produit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ajout_produit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ajout_produit.setIconTextGap(5);
        ajout_produit.setRadius(18);
        ajout_produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajout_produitMouseClicked(evt);
            }
        });

        supprimer_produit.setBackground(new java.awt.Color(255, 51, 51));
        supprimer_produit.setForeground(new java.awt.Color(51, 51, 51));
        supprimer_produit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-supprimer-pour-toujours-25.png"))); // NOI18N
        supprimer_produit.setText("Supprimer un produit");
        supprimer_produit.setBorderColor(new java.awt.Color(255, 51, 51));
        supprimer_produit.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        supprimer_produit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supprimer_produit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        supprimer_produit.setIconTextGap(5);
        supprimer_produit.setRadius(18);
        supprimer_produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimer_produitMouseClicked(evt);
            }
        });
        supprimer_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer_produitActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        modifier_produit.setBackground(new java.awt.Color(255, 153, 51));
        modifier_produit.setForeground(new java.awt.Color(51, 51, 51));
        modifier_produit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-modifier-25.png"))); // NOI18N
        modifier_produit.setText("Modifier un produit");
        modifier_produit.setBorderColor(new java.awt.Color(255, 153, 51));
        modifier_produit.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        modifier_produit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modifier_produit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        modifier_produit.setIconTextGap(5);
        modifier_produit.setRadius(18);
        modifier_produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifier_produitMouseClicked(evt);
            }
        });
        modifier_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier_produitActionPerformed(evt);
            }
        });

        ajout_categorie.setBackground(new java.awt.Color(0, 169, 54));
        ajout_categorie.setForeground(new java.awt.Color(51, 51, 51));
        ajout_categorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-plus-25.png"))); // NOI18N
        ajout_categorie.setText("Ajouter une catégorie");
        ajout_categorie.setBorderColor(new java.awt.Color(0, 169, 54));
        ajout_categorie.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        ajout_categorie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ajout_categorie.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ajout_categorie.setIconTextGap(5);
        ajout_categorie.setRadius(18);
        ajout_categorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajout_categorieMouseClicked(evt);
            }
        });
        ajout_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_categorieActionPerformed(evt);
            }
        });

        liste_produit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        liste_produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        liste_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        liste_produit.setRowHeight(30);
        liste_produit.setRowMargin(5);
        jScrollPane1.setViewportView(liste_produit);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ajout_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modifier_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(ajout_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimer_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajout_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifier_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajout_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void supprimer_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer_produitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimer_produitActionPerformed

    private void supprimer_produitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimer_produitMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer?", "SUPPRESSION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
               Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=utf-8","root","");
                //Recupération de la référence du produit à supprimer dans la table
                DefaultTableModel dt = (DefaultTableModel)liste_produit.getModel();
                //Ligne sélectionnée
                int rowindex = liste_produit.getSelectedRow();
                //Référence se trouve sur la colonne 0, ligne selectionnée
                String ref_prod_a_supprimer =(String) liste_produit.getValueAt(rowindex,0);  
                //Requete de suppression du produit
                String sql_req = "Delete from produit where ref_produit='"+ref_prod_a_supprimer+"'";
                //Création de l'objet statement
                st = co.createStatement();
                //Exécution de la requête
                st.executeUpdate(sql_req);
                //fermeture de la connexion
                co.close();
                //Suppression de la ligne de la table
                dt.removeRow(rowindex);
                //Message de suppression
                JOptionPane.showMessageDialog(null, "Données supprimées");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Problème de suppression");
            }
        }
    }//GEN-LAST:event_supprimer_produitMouseClicked

    private void ajout_produitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajout_produitMouseClicked
        new Nouveau_produit().setVisible(true);
    }//GEN-LAST:event_ajout_produitMouseClicked

    private void modifier_produitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifier_produitMouseClicked
        Nouveau_produit produit_a_modifier = new Nouveau_produit();
        
        produit_a_modifier.setVisible(true);
        /*
        PreparedStatement ps = null;
        if(JOptionPane.showConfirmDialog(null, "Voulez-vous modifier?", "Confirme Modif",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            co1 = DriverManager.getConnection("jdbc:mysql://localhost/mpsi?characterEncoding=latin1","root","");
            ps = co1.prepareStatement("Update etudiant SET matricule =?,nom=?,prenom=? where matricule =?");
            int i =new Integer(ide.getText());
            String n = no.getText();
            String p = pr.getText();

            int i2 =new Integer(oldID.getText());
            ps.setInt(1, i);
            ps.setString(2, n);
            ps.setString(3, p);
            ps.setInt(4,i2);
            

            ps.executeUpdate();
            
            System.out.println("OK");

            co1.close();
            ps.close();
            
            DefaultTableModel dt = (DefaultTableModel)table.getModel();
            int index = table.getSelectedRow();
            dt.setValueAt(i, index, 0);
            dt.setValueAt(n, index, 1);
            dt.setValueAt(p, index, 2);
            
            ide.setText("");
            no.setText("");
            pr.setText("");
            oldID.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problème de modification");
        }
        }
        
        */
    }//GEN-LAST:event_modifier_produitMouseClicked

    private void modifier_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_produitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifier_produitActionPerformed

    private void ajout_categorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajout_categorieMouseClicked
        new Categorie_Produit().setVisible(true);
    }//GEN-LAST:event_ajout_categorieMouseClicked

    private void ajout_categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajout_categorieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajout_categorie;
    private produitbio.Button_perso ajout_produit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable liste_produit;
    private javax.swing.JTable liste_user_table;
    private produitbio.Button_perso modifier_produit;
    private produitbio.Button_perso supprimer_produit;
    // End of variables declaration//GEN-END:variables
    Connection co;
    Statement st;
    ResultSet resultat;
    DefaultTableModel dtm = new DefaultTableModel();

}
