/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AISSAN Francois
 */
public class Liste_utilisateurs extends javax.swing.JPanel {

    /**
     * Creates new form Liste_utilisateurs
     */
    public Liste_utilisateurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("biomarket?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        utilisateurQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Utilisateur u");
        utilisateurList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : utilisateurQuery.getResultList();
        utilisateurQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Utilisateur u");
        utilisateurList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : utilisateurQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        essai = new javax.swing.JPanel();
        ajout_user = new produitbio.Button_perso();
        supprimer = new produitbio.Button_perso();

        setBackground(new java.awt.Color(217, 217, 217));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Liste des utilisateurs");

        essai.setBackground(new java.awt.Color(217, 217, 217));
        essai.setToolTipText("");

        javax.swing.GroupLayout essaiLayout = new javax.swing.GroupLayout(essai);
        essai.setLayout(essaiLayout);
        essaiLayout.setHorizontalGroup(
            essaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        essaiLayout.setVerticalGroup(
            essaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ajout_user.setBackground(new java.awt.Color(0, 169, 54));
        ajout_user.setForeground(new java.awt.Color(51, 51, 51));
        ajout_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-plus-25.png"))); // NOI18N
        ajout_user.setText("Ajouter");
        ajout_user.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        ajout_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ajout_user.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ajout_user.setIconTextGap(5);
        ajout_user.setRadius(18);
        ajout_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajout_userMouseClicked(evt);
            }
        });
        ajout_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_userActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(255, 102, 102));
        supprimer.setForeground(new java.awt.Color(51, 51, 51));
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produitbio/icons8-dashboard-colours/icons8-supprimer-pour-toujours-25.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        supprimer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supprimer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        supprimer.setIconTextGap(5);
        supprimer.setRadius(18);
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerMouseClicked(evt);
            }
        });
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ajout_user, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(essai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(essai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajout_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ajout_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajout_userMouseClicked
     essai.setBackground(Color.red);
        
        //dtm.addColumn("Id");
        
    }//GEN-LAST:event_ajout_userMouseClicked

    private void ajout_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_userActionPerformed

    }//GEN-LAST:event_ajout_userActionPerformed

    private void supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerMouseClicked

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajout_user;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel essai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private produitbio.Button_perso supprimer;
    private java.util.List<produitbio.Utilisateur> utilisateurList;
    private java.util.List<produitbio.Utilisateur> utilisateurList1;
    private javax.persistence.Query utilisateurQuery;
    private javax.persistence.Query utilisateurQuery1;
    // End of variables declaration//GEN-END:variables
    Connection co;
    Statement st;
    ResultSet resultat;
    DefaultTableModel dtm = new DefaultTableModel();

}
