/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AISSAN Francois
 */
public class Nouveau_Client extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Nouveau_Client() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo_bket.png")).getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        nom_prenom_client = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        message_error_cat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ajouter = new produitbio.Button_perso();
        annuler = new produitbio.Button_perso();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email_client = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telephone_client = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NOUVEAU CLIENT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nom_prenom_client.setBackground(new java.awt.Color(235, 235, 235));
        nom_prenom_client.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        nom_prenom_client.setForeground(new java.awt.Color(51, 51, 51));
        nom_prenom_client.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        nom_prenom_client.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom_prenom_client.setName(""); // NOI18N
        nom_prenom_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_prenom_clientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout d'un client");

        message_error_cat.setBackground(new java.awt.Color(255, 255, 255));
        message_error_cat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        message_error_cat.setForeground(new java.awt.Color(204, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nom et Prénoms");

        ajouter.setBackground(new java.awt.Color(0, 169, 54));
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter.setRadius(40);
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        annuler.setBackground(new java.awt.Color(0, 169, 54));
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Retour");
        annuler.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        annuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annuler.setRadius(40);
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 169, 54));
        jLabel2.setText("Bket.");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Email");

        email_client.setBackground(new java.awt.Color(235, 235, 235));
        email_client.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        email_client.setForeground(new java.awt.Color(51, 51, 51));
        email_client.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        email_client.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email_client.setName(""); // NOI18N
        email_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_clientActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Téléphone");

        telephone_client.setBackground(new java.awt.Color(235, 235, 235));
        telephone_client.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        telephone_client.setForeground(new java.awt.Color(51, 51, 51));
        telephone_client.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        telephone_client.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telephone_client.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(nom_prenom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(message_error_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addComponent(email_client, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telephone_client, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(nom_prenom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(email_client, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telephone_client, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message_error_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        this.dispose();
    }//GEN-LAST:event_annulerMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        //Les variables
        Color colorbgold =new Color(217,217,217);
        String nom_prenom_saisi = nom_prenom_client.getText();
        String email_saisi = email_client.getText();
        String telephone_saisi = telephone_client.getText();
        int point_client = 0;
        

        if (nom_prenom_client.equals("")||email_client.equals("")||telephone_client.equals("")){
            message_error_cat.setForeground(Color.RED);
            message_error_cat.setText("Veuillez remplir les champs !!!");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer l'ajout?", "CONFIRMATION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){                       
                try {
                        //connexion à la base de données
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        Connection co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=utf-8","root","");
                        Statement st = co.createStatement();

                        //Recuperer le texte saisi ref_client	nom_prenoms_client	email_client	telephone_client	point_client
                        st.executeUpdate("INSERT INTO client(nom_prenoms_client,email_client,telephone_client,point_client)values('"+nom_prenom_saisi+"','"+email_saisi+"','"+telephone_saisi+"','"+point_client+"')");

                        //vider le champ
                        nom_prenom_client.setText("");
                        email_client.setText("");
                        telephone_client.setText("");
                        
                        //Notification
                        message_error_cat.setForeground(colorbgold);
                        message_error_cat.setText("Client bien ajouté !!");
                        
                        //Thread.sleep(2000);
                                                
                } catch (Exception e) {
                   message_error_cat.setText("Problème de connexion !!");
                }
            }
            else
            {
                message_error_cat.setForeground(Color.RED);
                message_error_cat.setText("Données non ajoutées");
            }
        }

    }//GEN-LAST:event_ajouterMouseClicked

    private void nom_prenom_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_prenom_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_prenom_clientActionPerformed

    private void email_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_clientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nouveau_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajouter;
    private produitbio.Button_perso annuler;
    private javax.swing.JTextField email_client;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message_error_cat;
    private javax.swing.JTextField nom_prenom_client;
    private javax.swing.JTextField telephone_client;
    // End of variables declaration//GEN-END:variables
}
