/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AISSAN Francois
 */
public class Nouveau_fournisseur extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Nouveau_fournisseur() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo_bket.png")).getImage();
        this.setIconImage(img);
        
        try {
                //connexion à la base de données
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=latin1","root","");
                Statement st = co.createStatement();
                
                //Recuperation des resultats 
                                
        } catch (Exception e) {
           message_error.setText("Problème de connexion !!");
        }
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        message_error = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        ajouter = new produitbio.Button_perso();
        name_fournisseur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adr_fournisseur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        annuler = new produitbio.Button_perso();
        tel_fournisseur = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout d'un fournisseur");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-2, 14, 520, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Téléphone fournisseur");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 230, 139, 20);

        message_error.setBackground(new java.awt.Color(255, 255, 255));
        message_error.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        message_error.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(message_error);
        message_error.setBounds(130, 310, 256, 25);

        jTextField4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 169, 54));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Bket.");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(580, 532, 56, 32);

        ajouter.setBackground(new java.awt.Color(0, 169, 54));
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter.setRadius(40);
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter);
        ajouter.setBounds(130, 340, 125, 40);

        name_fournisseur.setBackground(new java.awt.Color(235, 235, 235));
        name_fournisseur.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        name_fournisseur.setForeground(new java.awt.Color(51, 51, 51));
        name_fournisseur.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        name_fournisseur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name_fournisseur.setName(""); // NOI18N
        name_fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fournisseurActionPerformed(evt);
            }
        });
        jPanel1.add(name_fournisseur);
        name_fournisseur.setBounds(110, 100, 304, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nom fournisseur");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 80, 105, 20);

        adr_fournisseur.setBackground(new java.awt.Color(235, 235, 235));
        adr_fournisseur.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        adr_fournisseur.setForeground(new java.awt.Color(51, 51, 51));
        adr_fournisseur.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        adr_fournisseur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        adr_fournisseur.setName(""); // NOI18N
        adr_fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adr_fournisseurActionPerformed(evt);
            }
        });
        jPanel1.add(adr_fournisseur);
        adr_fournisseur.setBounds(110, 180, 304, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Adresse fournisseur");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 160, 140, 20);

        annuler.setBackground(new java.awt.Color(0, 169, 54));
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Annuler");
        annuler.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        annuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annuler.setRadius(40);
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel1.add(annuler);
        annuler.setBounds(280, 340, 125, 40);

        tel_fournisseur.setBackground(new java.awt.Color(235, 235, 235));
        tel_fournisseur.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        tel_fournisseur.setForeground(new java.awt.Color(51, 51, 51));
        tel_fournisseur.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        tel_fournisseur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tel_fournisseur.setName(""); // NOI18N
        tel_fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_fournisseurActionPerformed(evt);
            }
        });
        jPanel1.add(tel_fournisseur);
        tel_fournisseur.setBounds(110, 260, 304, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tel_fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_fournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_fournisseurActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        this.dispose();
    }//GEN-LAST:event_annulerMouseClicked

    private void adr_fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adr_fournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adr_fournisseurActionPerformed

    private void name_fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fournisseurActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        Connection co = null;
        Statement st = null;
        ResultSet rs = null;
        ResultSet rs1 = null;

        //Les variables
        String v_name = name_fournisseur.getText();
        String v_adr = adr_fournisseur.getText();
        String v_tel = tel_fournisseur.getText();
        if (v_name.equals("")||v_adr.equals("")||v_tel.equals("")){
            message_error.setForeground(Color.red);
            message_error.setText("Veuillez remplir tous les champs !!!");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer l'ajout?", "CONFIRMATION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try {
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=latin1","root","");
                    st = co.createStatement();
                    st.executeUpdate("INSERT INTO fournisseur (nom_fournisseur,adresse_fournisseur,telephone_fournisseur) values ('"+v_name+"','"+v_adr+"','"+v_tel+"')");
                    //Réinitialisation des champs
                    name_fournisseur.setText("");
                    adr_fournisseur.setText("");
                    tel_fournisseur.setText("");
                    message_error.setForeground(Color.GREEN);
                    message_error.setText("Données bien enregistrées");

                } catch (Exception e) {
                    message_error.setText("Erreur");
                }
            }
            else
            {
                message_error.setText("Données non ajoutées");
            }
        }

    }//GEN-LAST:event_ajouterMouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau_fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau_fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau_fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau_fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nouveau_fournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr_fournisseur;
    private produitbio.Button_perso ajouter;
    private produitbio.Button_perso annuler;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel message_error;
    private javax.swing.JTextField name_fournisseur;
    private javax.swing.JTextField tel_fournisseur;
    // End of variables declaration//GEN-END:variables
}
