/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AISSAN Francois
 */
public class Nouveau_produit extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Nouveau_produit() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo_bket.png")).getImage();
        this.setIconImage(img);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        reference = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        message_error_cat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ajouter = new produitbio.Button_perso();
        annuler = new produitbio.Button_perso();
        jLabel2 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        date_production = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        date_expiration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        quantie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantie_alerte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        prix_vente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        categorie_poduit = new javax.swing.JComboBox();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NOUVEAU PRODUIT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 54), 3));
        jPanel1.setLayout(null);

        reference.setBackground(new java.awt.Color(235, 235, 235));
        reference.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        reference.setForeground(new java.awt.Color(51, 51, 51));
        reference.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        reference.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reference.setName(""); // NOI18N
        reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceActionPerformed(evt);
            }
        });
        jPanel1.add(reference);
        reference.setBounds(149, 114, 304, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout d'un produit");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(3, 30, 571, 40);

        message_error_cat.setBackground(new java.awt.Color(255, 255, 255));
        message_error_cat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        message_error_cat.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(message_error_cat);
        message_error_cat.setBounds(150, 650, 300, 25);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Référence");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 90, 62, 20);

        ajouter.setBackground(new java.awt.Color(0, 169, 54));
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter.setRadius(40);
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter);
        ajouter.setBounds(150, 690, 125, 40);

        annuler.setBackground(new java.awt.Color(0, 169, 54));
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Retour");
        annuler.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        annuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annuler.setRadius(40);
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel1.add(annuler);
        annuler.setBounds(330, 690, 125, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 169, 54));
        jLabel2.setText("Bket.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 730, 70, 32);

        libelle.setBackground(new java.awt.Color(235, 235, 235));
        libelle.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        libelle.setForeground(new java.awt.Color(51, 51, 51));
        libelle.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        libelle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        libelle.setName(""); // NOI18N
        libelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleActionPerformed(evt);
            }
        });
        jPanel1.add(libelle);
        libelle.setBounds(150, 180, 304, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Libellé");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 160, 41, 20);

        date_production.setBackground(new java.awt.Color(235, 235, 235));
        date_production.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        date_production.setForeground(new java.awt.Color(51, 51, 51));
        date_production.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        date_production.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        date_production.setName(""); // NOI18N
        date_production.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_productionActionPerformed(evt);
            }
        });
        jPanel1.add(date_production);
        date_production.setBounds(150, 250, 304, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Date de production");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 230, 121, 20);

        date_expiration.setBackground(new java.awt.Color(235, 235, 235));
        date_expiration.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        date_expiration.setForeground(new java.awt.Color(51, 51, 51));
        date_expiration.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        date_expiration.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        date_expiration.setName(""); // NOI18N
        date_expiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_expirationActionPerformed(evt);
            }
        });
        jPanel1.add(date_expiration);
        date_expiration.setBounds(150, 320, 304, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Date d'expiration");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 300, 108, 20);

        quantie.setBackground(new java.awt.Color(235, 235, 235));
        quantie.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        quantie.setForeground(new java.awt.Color(51, 51, 51));
        quantie.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        quantie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        quantie.setName(""); // NOI18N
        quantie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantieActionPerformed(evt);
            }
        });
        jPanel1.add(quantie);
        quantie.setBounds(150, 390, 304, 40);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Quantité");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 370, 55, 20);

        quantie_alerte.setBackground(new java.awt.Color(235, 235, 235));
        quantie_alerte.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        quantie_alerte.setForeground(new java.awt.Color(51, 51, 51));
        quantie_alerte.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        quantie_alerte.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        quantie_alerte.setName(""); // NOI18N
        quantie_alerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantie_alerteActionPerformed(evt);
            }
        });
        jPanel1.add(quantie_alerte);
        quantie_alerte.setBounds(150, 460, 304, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Quantité alerte");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 440, 120, 20);

        prix_vente.setBackground(new java.awt.Color(235, 235, 235));
        prix_vente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        prix_vente.setForeground(new java.awt.Color(51, 51, 51));
        prix_vente.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        prix_vente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        prix_vente.setName(""); // NOI18N
        prix_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prix_venteActionPerformed(evt);
            }
        });
        jPanel1.add(prix_vente);
        prix_vente.setBounds(150, 530, 304, 40);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Prix de vente");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(150, 510, 110, 20);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Categorie du produit");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 580, 170, 20);

        categorie_poduit.setBackground(new java.awt.Color(235, 235, 235));
        categorie_poduit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(categorie_poduit);
        categorie_poduit.setBounds(150, 600, 300, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        this.dispose();
    }//GEN-LAST:event_annulerMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        //Les variables
        Color colorbgold =new Color(217,217,217);
        String libelle_saisi = reference.getText();


        if (libelle_saisi.equals("")){
            message_error_cat.setForeground(Color.RED);
            message_error_cat.setText("Veuillez remplir le champ !!!");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer l'ajout?", "CONFIRMATION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        
                try {
                        //connexion à la base de données
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        Connection co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=UTF-8","root","");
                        Statement st = co.createStatement();

                        //Recuperer le texte saisi
                        System.out.println(libelle_saisi);
                        st.executeUpdate("INSERT INTO cat_produit(libelle_cat)values('"+libelle_saisi+"')");
                        //vider le champ
                        reference.setText("");
                        
                        message_error_cat.setForeground(colorbgold);
                        message_error_cat.setText("Categorie bien ajoutée !!");
                        
                        //Thread.sleep(2000);
                        
                        

                } catch (Exception e) {
                   message_error_cat.setText("Problème de connexion !!");
                }
            }
            else
            {
                message_error_cat.setForeground(Color.RED);
                message_error_cat.setText("Données non ajoutées");
            }
        }

    }//GEN-LAST:event_ajouterMouseClicked

    private void referenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceActionPerformed

    private void libelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleActionPerformed

    private void date_productionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_productionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_productionActionPerformed

    private void date_expirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_expirationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_expirationActionPerformed

    private void quantieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantieActionPerformed

    private void quantie_alerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantie_alerteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantie_alerteActionPerformed

    private void prix_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prix_venteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prix_venteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nouveau_produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajouter;
    private produitbio.Button_perso annuler;
    private javax.swing.JComboBox categorie_poduit;
    private javax.swing.JTextField date_expiration;
    private javax.swing.JTextField date_production;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libelle;
    private javax.swing.JLabel message_error_cat;
    private javax.swing.JTextField prix_vente;
    private javax.swing.JTextField quantie;
    private javax.swing.JTextField quantie_alerte;
    private javax.swing.JTextField reference;
    // End of variables declaration//GEN-END:variables
}
