/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AISSAN Francois
 */
public class Nouveau_produit extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Nouveau_produit() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo_bket.png")).getImage();
        this.setIconImage(img);
        
        //Affichage des catégories des produits automatique à l'ouverture de la fenetre
        try {
                //connexion à la base de données
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=latin1","root","");
                st = co.createStatement();
                
                //Recuperation des resultats 
                rs = st.executeQuery("SELECT libelle_cat FROM cat_produit");
                
                while(rs.next()){
                   String categorie_produit = rs.getString("libelle_cat");
                   categorie_poduit.addItem(categorie_produit);
                }
                
        } catch (Exception e) {
           message_error_cat.setText("Problème de connexion !!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        reference = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        message_error_cat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ajouter = new produitbio.Button_perso();
        annuler = new produitbio.Button_perso();
        jLabel2 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        quantite = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantite_alerte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        prix_vente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        categorie_poduit = new javax.swing.JComboBox();
        date_production = new org.jdesktop.swingx.JXDatePicker();
        date_expiration = new org.jdesktop.swingx.JXDatePicker();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NOUVEAU PRODUIT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 54), 3));
        jPanel1.setLayout(null);

        reference.setBackground(new java.awt.Color(235, 235, 235));
        reference.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        reference.setForeground(new java.awt.Color(51, 51, 51));
        reference.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        reference.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reference.setName(""); // NOI18N
        reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceActionPerformed(evt);
            }
        });
        jPanel1.add(reference);
        reference.setBounds(40, 120, 304, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout d'un produit");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, 30, 750, 40);

        message_error_cat.setBackground(new java.awt.Color(255, 255, 255));
        message_error_cat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        message_error_cat.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(message_error_cat);
        message_error_cat.setBounds(220, 380, 300, 25);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Référence");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 100, 62, 20);

        ajouter.setBackground(new java.awt.Color(0, 169, 54));
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter.setRadius(40);
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter);
        ajouter.setBounds(170, 420, 170, 40);

        annuler.setBackground(new java.awt.Color(0, 169, 54));
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Retour");
        annuler.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        annuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annuler.setRadius(40);
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel1.add(annuler);
        annuler.setBounds(400, 420, 170, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 169, 54));
        jLabel2.setText("Bket.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 470, 60, 32);

        libelle.setBackground(new java.awt.Color(235, 235, 235));
        libelle.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        libelle.setForeground(new java.awt.Color(51, 51, 51));
        libelle.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        libelle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        libelle.setName(""); // NOI18N
        libelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleActionPerformed(evt);
            }
        });
        jPanel1.add(libelle);
        libelle.setBounds(40, 190, 304, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Libellé");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 170, 41, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Date de production");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 240, 121, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Date d'expiration");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 310, 108, 20);

        quantite.setBackground(new java.awt.Color(235, 235, 235));
        quantite.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        quantite.setForeground(new java.awt.Color(51, 51, 51));
        quantite.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        quantite.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        quantite.setName(""); // NOI18N
        quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantiteActionPerformed(evt);
            }
        });
        jPanel1.add(quantite);
        quantite.setBounds(400, 120, 304, 40);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Quantité");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 100, 55, 20);

        quantite_alerte.setBackground(new java.awt.Color(235, 235, 235));
        quantite_alerte.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        quantite_alerte.setForeground(new java.awt.Color(51, 51, 51));
        quantite_alerte.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        quantite_alerte.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        quantite_alerte.setName(""); // NOI18N
        quantite_alerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantite_alerteActionPerformed(evt);
            }
        });
        jPanel1.add(quantite_alerte);
        quantite_alerte.setBounds(400, 190, 304, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Quantité alerte");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 170, 120, 20);

        prix_vente.setBackground(new java.awt.Color(235, 235, 235));
        prix_vente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        prix_vente.setForeground(new java.awt.Color(51, 51, 51));
        prix_vente.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        prix_vente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        prix_vente.setName(""); // NOI18N
        prix_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prix_venteActionPerformed(evt);
            }
        });
        jPanel1.add(prix_vente);
        prix_vente.setBounds(400, 260, 304, 40);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Prix de vente");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 240, 110, 20);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Categorie du produit");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 310, 170, 20);

        categorie_poduit.setBackground(new java.awt.Color(235, 235, 235));
        categorie_poduit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(categorie_poduit);
        categorie_poduit.setBounds(400, 330, 300, 40);

        date_production.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        date_production.setFormats("dd/MM/yyyy");
        date_production.setName(""); // NOI18N
        jPanel1.add(date_production);
        date_production.setBounds(40, 270, 300, 40);

        date_expiration.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        date_expiration.setFormats("dd/MM/yyyy");
        jPanel1.add(date_expiration);
        date_expiration.setBounds(40, 330, 300, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        this.dispose();
    }//GEN-LAST:event_annulerMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        //Les variables
        Color colorbgold =new Color(217,217,217);
        
        String reference_saisie = reference.getText();
        String libelle_saisie = libelle.getText();
        
        //date_production.setFormats("dd/MM/yyyy");
        String d_production = date_production.getDate().toString();
        
        //date_expiration.setFormats("dd/MM/yyyy");
        String d_expiration = date_expiration.getDate().toString();
        
        String quantite_saisie = quantite.getText();//A convertir
        String quantite_alerte_saisie = quantite_alerte.getText();//A convertir
        String prix_vente_saisie = prix_vente.getText();//A convertir
        String categorie_choisie = categorie_poduit.getSelectedItem().toString();//A convertir

        if (reference_saisie.equals("")
                ||libelle_saisie.equals("")
                ||d_production.equals("")
                ||d_expiration.equals("")
                ||quantite_saisie.equals("")
                ||quantite_alerte_saisie.equals("")
                ||prix_vente_saisie.equals("")){
            message_error_cat.setForeground(Color.RED);
            message_error_cat.setText("Veuillez remplir le champ !!!");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer l'ajout?", "CONFIRMATION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        
                try {
                        //connexion à la base de données
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=UTF-8","root","");
                        st = co.createStatement();
                        
                        //Conversion
                        Double quantite_saisie_converti = new Double(quantite_saisie);
                        Double quantite_alerte_saisie_converti = new Double(quantite_alerte_saisie);
                        Double prix_vente_saisie_converti = new Double(prix_vente_saisie);
                        
                        
                        rs = st.executeQuery("SELECT id_cat FROM cat_produit WHERE libelle_cat ='"+categorie_choisie+"'");
                    
                        int num_int_categorie = 0;
                        if(rs.next())
                        {
                            num_int_categorie = rs.getInt(1);
                        }   
                        
                        //Recuperer le texte saisi
                        st.executeUpdate("INSERT INTO produit(ref_produit,lib_produit,date_production,date_expiration,quantite,quantite_alerte,prix_vente,categorie_produit)values('"+reference_saisie+"','"+libelle_saisie+"','"+d_production+"','"+d_expiration+"','"+quantite_saisie_converti+"','"+quantite_alerte_saisie_converti+"','"+prix_vente_saisie_converti+"','"+num_int_categorie+"')");
                        
                        
                        //vider le champ
                        reference.setText("");
                        libelle.setText("");
                        //date_production.setText("");
                        //date_expiration.;
                        quantite.setText("");
                        quantite_alerte.setText("");
                        prix_vente.setText("");
                        
                        //Notification d'ajout
                        message_error_cat.setForeground(colorbgold);
                        message_error_cat.setText("Produit bien ajouté !!");
                        
                        //Thread.sleep(2000);
                } catch (Exception e) {
                   message_error_cat.setText("Problème de connexion !!");
                }
            }
            else
            {
                message_error_cat.setForeground(Color.RED);
                message_error_cat.setText("Produit non ajouté");
            }
        }

    }//GEN-LAST:event_ajouterMouseClicked

    private void referenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceActionPerformed

    private void libelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleActionPerformed

    private void quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteActionPerformed

    private void quantite_alerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantite_alerteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantite_alerteActionPerformed

    private void prix_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prix_venteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prix_venteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau_produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nouveau_produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajouter;
    private produitbio.Button_perso annuler;
    private javax.swing.JComboBox categorie_poduit;
    private org.jdesktop.swingx.JXDatePicker date_expiration;
    private org.jdesktop.swingx.JXDatePicker date_production;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libelle;
    private javax.swing.JLabel message_error_cat;
    private javax.swing.JTextField prix_vente;
    private javax.swing.JTextField quantite;
    private javax.swing.JTextField quantite_alerte;
    private javax.swing.JTextField reference;
    // End of variables declaration//GEN-END:variables
        ResultSet rs = null;
        Statement st = null;
        Connection co = null;
}
