/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

/**
 *
 * @author AISSAN Francois
 */
public class Nouvelle_Vente extends javax.swing.JPanel {

    /**
     * Creates new form Nouvelle_Vente
     */
    public Nouvelle_Vente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ajouter1 = new produitbio.Button_perso();
        ajouter2 = new produitbio.Button_perso();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        nom6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nom7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ajouter3 = new produitbio.Button_perso();
        ajouter4 = new produitbio.Button_perso();
        ajouter5 = new produitbio.Button_perso();
        jPanel6 = new javax.swing.JPanel();
        nom8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nom9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nom10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Validation Vente");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(150, 20, 140, 25);

        ajouter1.setBackground(new java.awt.Color(0, 169, 54));
        ajouter1.setForeground(new java.awt.Color(255, 255, 255));
        ajouter1.setText("Valider vente");
        ajouter1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter1.setRadius(40);
        ajouter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouter1MouseClicked(evt);
            }
        });
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });
        jPanel3.add(ajouter1);
        ajouter1.setBounds(40, 70, 170, 33);

        ajouter2.setBackground(new java.awt.Color(0, 169, 54));
        ajouter2.setForeground(new java.awt.Color(255, 255, 255));
        ajouter2.setText("Imprimer facture");
        ajouter2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter2.setRadius(40);
        ajouter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouter2MouseClicked(evt);
            }
        });
        ajouter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter2ActionPerformed(evt);
            }
        });
        jPanel3.add(ajouter2);
        ajouter2.setBounds(240, 70, 200, 33);

        add(jPanel3);
        jPanel3.setBounds(10, 630, 450, 150);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Produits ajoutés");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(290, 20, 140, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Désignation", "Quantité", "Prix unitaire", "Montant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 670, 680);

        add(jPanel4);
        jPanel4.setBounds(490, 10, 700, 770);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        nom6.setBackground(new java.awt.Color(235, 235, 235));
        nom6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        nom6.setForeground(new java.awt.Color(51, 51, 51));
        nom6.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        nom6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom6.setName(""); // NOI18N
        nom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom6ActionPerformed(evt);
            }
        });
        jPanel5.add(nom6);
        nom6.setBounds(170, 150, 201, 40);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Ref. produit");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(50, 90, 90, 20);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Quantité");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(50, 160, 70, 20);

        nom7.setBackground(new java.awt.Color(235, 235, 235));
        nom7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        nom7.setForeground(new java.awt.Color(51, 51, 51));
        nom7.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        nom7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom7.setName(""); // NOI18N
        nom7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom7ActionPerformed(evt);
            }
        });
        jPanel5.add(nom7);
        nom7.setBounds(170, 80, 201, 40);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Ajout des produits");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(150, 20, 170, 25);

        ajouter3.setBackground(new java.awt.Color(0, 169, 54));
        ajouter3.setForeground(new java.awt.Color(255, 255, 255));
        ajouter3.setText("Supprimer");
        ajouter3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter3.setRadius(40);
        ajouter3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouter3MouseClicked(evt);
            }
        });
        ajouter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter3ActionPerformed(evt);
            }
        });
        jPanel5.add(ajouter3);
        ajouter3.setBounds(300, 220, 120, 33);

        ajouter4.setBackground(new java.awt.Color(0, 169, 54));
        ajouter4.setForeground(new java.awt.Color(255, 255, 255));
        ajouter4.setText("Ajouter");
        ajouter4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter4.setRadius(40);
        ajouter4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouter4MouseClicked(evt);
            }
        });
        ajouter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter4ActionPerformed(evt);
            }
        });
        jPanel5.add(ajouter4);
        ajouter4.setBounds(50, 220, 110, 33);

        ajouter5.setBackground(new java.awt.Color(0, 169, 54));
        ajouter5.setForeground(new java.awt.Color(255, 255, 255));
        ajouter5.setText("Modifier");
        ajouter5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter5.setRadius(40);
        ajouter5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouter5MouseClicked(evt);
            }
        });
        ajouter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter5ActionPerformed(evt);
            }
        });
        jPanel5.add(ajouter5);
        ajouter5.setBounds(170, 220, 120, 33);

        add(jPanel5);
        jPanel5.setBounds(10, 310, 450, 290);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        nom8.setBackground(new java.awt.Color(235, 235, 235));
        nom8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        nom8.setForeground(new java.awt.Color(51, 51, 51));
        nom8.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        nom8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom8.setName(""); // NOI18N
        nom8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom8ActionPerformed(evt);
            }
        });
        jPanel6.add(nom8);
        nom8.setBounds(160, 140, 201, 40);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Entete facture de vente");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(140, 20, 200, 25);

        nom9.setBackground(new java.awt.Color(235, 235, 235));
        nom9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        nom9.setForeground(new java.awt.Color(51, 51, 51));
        nom9.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        nom9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom9.setName(""); // NOI18N
        nom9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom9ActionPerformed(evt);
            }
        });
        jPanel6.add(nom9);
        nom9.setBounds(160, 220, 201, 40);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Client");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(40, 150, 37, 20);

        nom10.setBackground(new java.awt.Color(235, 235, 235));
        nom10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        nom10.setForeground(new java.awt.Color(51, 51, 51));
        nom10.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        nom10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom10.setName(""); // NOI18N
        nom10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom10ActionPerformed(evt);
            }
        });
        jPanel6.add(nom10);
        nom10.setBounds(160, 70, 201, 40);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Date de vente");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(40, 230, 91, 20);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Ref. vente");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(40, 80, 62, 20);

        add(jPanel6);
        jPanel6.setBounds(10, 10, 450, 290);
    }// </editor-fold>//GEN-END:initComponents

    private void ajouter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter1MouseClicked

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter1ActionPerformed

    private void nom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom6ActionPerformed

    private void nom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom7ActionPerformed

    private void ajouter3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter3MouseClicked

    private void ajouter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter3ActionPerformed

    private void ajouter4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter4MouseClicked

    private void ajouter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter4ActionPerformed

    private void ajouter5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter5MouseClicked

    private void ajouter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter5ActionPerformed

    private void ajouter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter2ActionPerformed

    private void ajouter2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter2MouseClicked

    private void nom8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom8ActionPerformed

    private void nom9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom9ActionPerformed

    private void nom10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajouter1;
    private produitbio.Button_perso ajouter2;
    private produitbio.Button_perso ajouter3;
    private produitbio.Button_perso ajouter4;
    private produitbio.Button_perso ajouter5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nom10;
    private javax.swing.JTextField nom6;
    private javax.swing.JTextField nom7;
    private javax.swing.JTextField nom8;
    private javax.swing.JTextField nom9;
    // End of variables declaration//GEN-END:variables
}
