/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produitbio;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AISSAN Francois
 */
public class Nouvelle_livraison extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Nouvelle_livraison() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo_bket.png")).getImage();
        this.setIconImage(img);
        
        try {
                //connexion à la base de données
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=latin1","root","");
                st = co.createStatement();
                
                //Recuperation des resultats 
                rs = st.executeQuery("SELECT nom_fournisseur FROM fournisseur");
                while(rs.next()){
                   String libele_fournisseur = rs.getString("nom_fournisseur");
                   nom_fournisseur.addItem(libele_fournisseur);
                }
                
                rs = st.executeQuery("SELECT lib_produit FROM produit");
                while(rs.next()){
                   String libele_produit = rs.getString("lib_produit");
                   nom_produit.addItem(libele_produit);
                }
                
        } catch (Exception e) {
           message_error.setText("Problème de connexion !!");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        message_error = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ajouter = new produitbio.Button_perso();
        quantite_prod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nom_produit = new javax.swing.JComboBox();
        annuler = new produitbio.Button_perso();
        nom_fournisseur = new javax.swing.JComboBox();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout d'une livraison");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 11, 492, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Quantité produit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(97, 260, 105, 20);

        message_error.setBackground(new java.awt.Color(255, 255, 255));
        message_error.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        message_error.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(message_error);
        message_error.setBounds(103, 337, 250, 25);

        jTextField4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 169, 54));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Bket.");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(577, 547, 56, 32);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nom produit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(97, 97, 81, 20);

        ajouter.setBackground(new java.awt.Color(0, 169, 54));
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ajouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajouter.setRadius(40);
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        jPanel1.add(ajouter);
        ajouter.setBounds(90, 370, 125, 40);

        quantite_prod.setBackground(new java.awt.Color(235, 235, 235));
        quantite_prod.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        quantite_prod.setForeground(new java.awt.Color(51, 51, 51));
        quantite_prod.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 2, 2, 2));
        quantite_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        quantite_prod.setName(""); // NOI18N
        jPanel1.add(quantite_prod);
        quantite_prod.setBounds(97, 291, 270, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nom fournisseur");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(97, 181, 105, 20);

        nom_produit.setBackground(new java.awt.Color(235, 235, 235));
        nom_produit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(nom_produit);
        nom_produit.setBounds(97, 123, 270, 40);

        annuler.setBackground(new java.awt.Color(0, 169, 54));
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Annuler");
        annuler.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        annuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annuler.setRadius(40);
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        jPanel1.add(annuler);
        annuler.setBounds(240, 370, 125, 40);

        nom_fournisseur.setBackground(new java.awt.Color(235, 235, 235));
        nom_fournisseur.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(nom_fournisseur);
        nom_fournisseur.setBounds(97, 213, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        this.dispose();
    }//GEN-LAST:event_annulerMouseClicked

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked

        
        String v_fournisseur = nom_fournisseur.getSelectedItem().toString();
        String v_produit = nom_produit.getSelectedItem().toString();
        String v_quantite = quantite_prod.getText();
        String v_date = new SimpleDateFormat().format(new Date());    
        String ref_prod = "";
        int num_int_fournisseur = 0;
        double quantite_prod_restante =  0;
        double quantite_prod_maj =  0;

        if (v_quantite.equals("")||v_fournisseur.equals("")||v_produit.equals("")||v_date.equals("")){
            message_error.setForeground(Color.red);
            message_error.setText("Veuillez remplir tous les champs !!!");
        }
        
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer l'approvisionnement?", "CONFIRMATION",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try {
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    co = DriverManager.getConnection("jdbc:mysql://localhost/biomarket?characterEncoding=latin1","root","");
                    st = co.createStatement();
                    Double quantite_converti = new Double(v_quantite);
                    rs = st.executeQuery("SELECT ref_produit,quantite FROM produit WHERE lib_produit = '"+v_produit+"'");
                    if(rs.next())
                    {
                        ref_prod =  rs.getString("ref_produit");
                        quantite_prod_restante = rs.getDouble("quantite");
                    }
                                        
                    rs2 = st.executeQuery("SELECT reference_fournisseur FROM fournisseur WHERE nom_fournisseur = '"+v_fournisseur+"'");
   
                    if(rs2.next())
                    {
                        num_int_fournisseur =  rs2.getInt(1);
                    }
                    st.executeUpdate("INSERT INTO livraison (prod_liv, fournisseur_liv,quantite_liv,date_liv) values ('"+ref_prod+"',"+num_int_fournisseur+","+quantite_converti+",'"+v_date+"')");
                    
                    //Recupération de la quantité restante du produit

                    //Mise à jour de la quantité en stock du produit
                    quantite_prod_maj = quantite_prod_restante + quantite_converti;
                    System.out.println(quantite_prod_maj);
                    st.executeUpdate("UPDATE produit SET quantite="+quantite_prod_maj+" where ref_produit='"+ref_prod+"'");                
                    //Réinitialisation des champs
                    quantite_prod.setText("");
                    message_error.setForeground(Color.GREEN);
                    message_error.setText("Données bien enregistrées");
                } catch (Exception e) {
                    message_error.setText("Erreur");
                }
            }
            else
            {
                message_error.setText("Données non ajoutées");
            }
        }

    }//GEN-LAST:event_ajouterMouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouvelle_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouvelle_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouvelle_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouvelle_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nouvelle_livraison().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private produitbio.Button_perso ajouter;
    private produitbio.Button_perso annuler;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel message_error;
    private javax.swing.JComboBox nom_fournisseur;
    private javax.swing.JComboBox nom_produit;
    private javax.swing.JTextField quantite_prod;
    // End of variables declaration//GEN-END:variables
    Connection co = null;
    Statement st = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;

}
